<?php

namespace ThemeAtelier\Eventful\Admin\Views\Generator;

use ThemeAtelier\Eventful\Admin\Framework\Classes\Eventful;

if (!defined('ABSPATH')) {
	die;
} // Cannot access directly.

/**
 * The Layout building class.
 */
class EventfulDisplay
{

	/**
	 * Display options section metabox.
	 *
	 * @param string $prefix The metabox key.
	 * @return void
	 */
	public static function section($prefix)
	{
		Eventful::createSection(
			$prefix,
			array(
				'title'  => esc_html__('DISPLAY OPTIONS', 'eventful'),
				'icon'   => 'icofont-listine-dots',
				'class'   => 'display_options',
				'fields' => array(
					array(
						'type' => 'section_tab',
						'tabs' => array(
							array(
								'title' => esc_html__('General', 'eventful'),
								'icon'  => 'icofont-gears',
								'fields' => array(
									array(
										'id'         => 'section_title',
										'type'       => 'switcher',
										'title'      => esc_html__('Section Title ', 'eventful'),
										'subtitle' => esc_html__('Show/Hide item showcase section title.', 'eventful'),
										'text_on'    => esc_html__('Show', 'eventful'),
										'text_off'   => esc_html__('Hide', 'eventful'),
										'text_width' => 75,
									),
									array(
										'id'              => 'section_title_margin',
										'type'            => 'spacing',
										'title'      => esc_html__('Section Title Margin', 'eventful'),
										'subtitle' => esc_html__('Set margin for the section title.', 'eventful'),
										'units'           => array(
											'px',
										),
										'all_placeholder' => 'margin',
										'default'         => array(
											'top'    => '0',
											'right'  => '0',
											'bottom' => '30',
											'left' => '0',
										),
										'dependency'      => array(
											'section_title',
											'==',
											'true',
											true,
										),
									),
									array(
										'id'       => 'eventful_number_of_columns',
										'type'     => 'column',
										'title'      => esc_html__('Column(s)', 'eventful'),
										'desc' => esc_html__('Set number of column(s) in different devices for responsive view.', 'eventful'),
										'title_help' => '<i class="icofont-imac"></i> <b>' . esc_html__('Large Desktop', 'eventful') . '</b> - ' . esc_html__('width', 'eventful') . ' &gt; 1200px<br>' . '<i class="icofont-monitor"></i> <b>' . esc_html__('Desktop', 'eventful') . '</b> - ' . esc_html__('width', 'eventful') . ' &gt; 992px<br>' . '<i class="icofont-laptop-alt"></i> <b>' . esc_html__('Tablet', 'eventful') . '</b> - ' . esc_html__('width', 'eventful') . ' &gt; 768px<br>' .
											'<i class="icofont-ipad"></i> <b>' . esc_html__('Mobile Landscape', 'eventful') . '</b> - ' . esc_html__('width', 'eventful') . ' &gt; 576px<br>' . '<i class="icofont-android-tablet"></i> <b>' . esc_html__('Mobile', 'eventful') . '</b> - ' . esc_html__('width', 'eventful') . ' &lt;= 576px',
										'default'  => array(
											'lg_desktop'       => '3',
											'desktop'          => '3',
											'tablet'           => '2',
											'mobile_landscape' => '1',
											'mobile'           => '1',
										),
										'min'      => '1',
										'dependency' => array('eventful_layout_preset', 'any', 'carousel_layout,grid_layout,filter_layout,large_with_small', true),
									),
									array(
										'id'              => 'margin_between_event',
										'type'            => 'spacing',
										'title'      => esc_html__('Margin Between Columns', 'eventful'),
										'subtitle' => esc_html__('Set margin between columns (items).', 'eventful'),
										'all'             => true,
										'all_icon'        => '<i class="icofont-drag"></i>',
										'units'           => array(
											'px',
										),
										'all_placeholder' => 'margin',
										'default'         => array(
											'all' => '20',
										),
									),
									array(
										'id'         => 'item_same_height',
										'type'       => 'switcher',
										'title'      => esc_html__('Same Height', 'eventful'),
										'subtitle' => esc_html__('Enable to make all items/slides the same height as the tallest one.', 'eventful'),
										'default'    => false,
										'text_on'  => esc_html__('Enabled', 'eventful'),
										'text_off' => esc_html__('Disabled', 'eventful'),
										'text_width' => 94,
										'class'    => 'switcher_pro_only',
										'dependency' => array('eventful_layout_preset', 'any', 'carousel_layout,grid_layout,filter_layout,large_with_small', true),
									),

									array(
										'id'       => 'eventful_event_border',
										'type'     => 'border',
										'title'    => esc_html__('Border', 'eventful'),
										'subtitle' => esc_html__('Set border for the item.', 'eventful'),
										'all'      => true,
										'default'  => array(
											'all'   => '0',
											'style' => 'solid',
										),
									),
									array(
										'id'       => 'eventful_event_border_radius',
										'type'     => 'spacing',
										'title'    => esc_html__('Border Radius', 'eventful'),
										'subtitle' => esc_html__('Set border radius for item.', 'eventful'),
										'all'      => true,
										'units'    => array('px', '%'),
										'default'  => array(
											'all' => '10',
										),
									),
									array(
										'id'       => 'show_eventful_event_box_shadow',
										'type'     => 'checkbox',
										'title'    => esc_html__('Box-Shadow', 'eventful'),
										'subtitle' => esc_html__('Show box-shadow for the item.', 'eventful'),
										'default'  => true,
									),
									array(
										'id'         => 'eventful_event_box_shadow',
										'type'       => 'box_shadow',
										'title'      => esc_html__('Box-Shadow Values', 'eventful'),
										'subtitle' => esc_html__('Set box-shadow property values for the item.', 'eventful'),
										'default'    => array(
											'horizontal' => '0',
											'vertical'   => '0',
											'blur'       => '6',
											'spread'     => '-2',
											'color'      => 'rgb(187, 187, 187)',
										),
										'dependency' => array('show_eventful_event_box_shadow', '==', 'true'),
									),

									array(
										'id'       => 'eventful_event_inner_padding',
										'type'     => 'spacing',
										'title'    => esc_html__('Inner Padding', 'eventful'),
										'subtitle' => esc_html__('Set inner padding for item.', 'eventful'),
										'default'  => array(
											'top'    => '0',
											'right'  => '0',
											'bottom' => '0',
											'left'   => '0',
											'unit'   => 'px',
										),
									),
									array(
										'id'       => 'eventful_event_background',
										'type'     => 'color_group',
										'title'    => esc_html__('Background', 'eventful'),
										'subtitle' => esc_html__('Set background color for the item.', 'eventful'),
										'options'   => array(
											'color' => esc_html__('Color', 'eventful'),
											'hover_color' => esc_html__('Hover Color', 'eventful'),
										),
									),
									array(
										'id'       => 'eventful_featured_event_background',
										'type'     => 'color_group',
										'title'    => esc_html__('Featured Events Background', 'eventful'),
										'subtitle' => esc_html__('Set featured events background color for the item.', 'eventful'),
										'options'   => array(
											'color' => esc_html__('Color', 'eventful'),
											'hover_color' => esc_html__('Hover Color', 'eventful'),
										),
									),
									array(
										'id'         => 'show_preloader',
										'type'       => 'switcher',
										'title'      => esc_html__('Preloader', 'eventful'),
										'subtitle' => esc_html__('Items will be hidden until page load completed.', 'eventful'),
										'text_on'    => esc_html__('Enabled', 'eventful'),
										'text_off'   => esc_html__('Disabled', 'eventful'),
										'text_width' => 100,
										'default'    => false,
									),
								)
							),

							array(
								'title' => esc_html__('Template Styles', 'eventful'),
								'icon'  => 'icofont-edit',
								'fields' => array(
									array(
										'id'         => 'template_style',
										'class'      => 'template_style',
										'type'       => 'button_set',
										'title'      => esc_html__('Template Type', 'eventful'),
										'subtitle' => __('Choose whether to use a custom template or a pre-made layout.', 'eventful'),
										'title_help' => '<div class="eventful-info-content">' . __('Custom lets you fully control the layout. Pre-made Templates provide ready-to-use designs you can customize.', 'eventful') . '</div><a class="tooltip_btn_primary" target="_blank" href="' . esc_url(EVENTFUL_DEMO_URL . 'docs/display-options/?ref=1#template-styles') . '">' . esc_html__('Open Docs', 'eventful') . '</a>',
										'options'    => array(
											'custom'   => __('Custom', 'eventful'),
											'pre-made' => __('Pre-made Templates', 'eventful'),
										),
										'default'    => 'custom',
										'dependency' => array('eventful_layout_preset', '!=', 'list_layout', 'any'),
									),
									array(
										'id'       => 'content_template_style',
										'type'     => 'layout_preset',
										'title'    => esc_html__('Event Content Position', 'eventful'),
										'subtitle' => esc_html__('Choose where the event content will be positioned in the layout.', 'eventful'),
										'class'    => 'content_template_style',
										'options'  => array(
											'default'     => array(
												'image' => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/default.svg',
												'text'  => esc_html__('Default', 'eventful'),
												'option_demo_url' => EVENTFUL_DEMO_URL . 'events-carousel/#default',
											),
											'on_right'     => array(
												'image' => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/event-right.svg',
												'text'  => esc_html__('Right', 'eventful'),
												'option_demo_url' => EVENTFUL_DEMO_URL . 'events-carousel/#default',
												'pro_only' => true,
											),
											'on_left'     => array(
												'image' => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/event-left.svg',
												'text'  => esc_html__('Left', 'eventful'),
												'option_demo_url' => EVENTFUL_DEMO_URL . 'events-carousel/#default',
												'pro_only' => true,
											),
											'overlay'     => array(
												'image'    => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/overlay.svg',
												'text'     => esc_html__('Overlay', 'eventful'),
												'option_demo_url' => EVENTFUL_DEMO_URL . 'center-carousel/#overlay',
												'pro_only' => true,
											),
										),
										'default'  => 'default',
										'dependency' => array('eventful_layout_preset|template_style', 'not-any|==', 'list_layout,minimal_list|custom', 'any'),
									),
									array(
										'id'      => 'event_alignment',
										'type'    => 'button_set',
										'title'   => esc_html__('Alignment', 'eventful'),
										'desc' => esc_html__('Set the alignment for event.', 'eventful'),
										'options' => array(
											'left'   => '<i class="icofont-align-left" title="Left"></i>',
											'center' => '<i class="icofont-align-center" title="Center"></i>',
											'right'  => '<i class="icofont-align-right" title="Right"></i>',
										),
										'default' => 'left',
										'dependency' => array('eventful_layout_preset|template_style', 'not-any|==', 'list_layout,minimal_list|custom', 'any'),
									),
									array(
										'id'         => 'theme_style_minimal_list',
										'class'      => 'theme_style_minimal_list',
										'preview'    => 'minimal_list',
										'type'       => 'select',
										'title'      => esc_html__('Template Style Minimal List', 'eventful'),
										'title_help' => '<div class="eventful-info-label">' . esc_html__('Choose from available ready-made templates to control how events are displayed.', 'eventful') . '</div><a class="tooltip_btn_primary" target="_blank" href="' . esc_url(EVENTFUL_DEMO_URL . 'docs/display-options/?ref=1#template-styles') . '">' . esc_html__('Open Docs', 'eventful') . '</a> <a class="tooltip_btn_secondary" target="_blank" href="' . esc_url(EVENTFUL_DEMO_URL . 'pre-made-event-templates/') . '">' . esc_html__('Demo', 'eventful') . '</a>',
										'subtitle' => esc_html__('Select which template style you want to display.', 'eventful'),
										'options'    => array(
											'theme-one'   => esc_html__('Template One', 'eventful'),
											'theme-two'   => esc_html__('Template Two', 'eventful'),
											'theme-three'   => esc_html__('Template Three', 'eventful'),
										),
										'default'    => 'theme-one',
										'dependency' => array('eventful_layout_preset|template_style', '==|==', 'minimal_list|pre-made', 'any'),
									),
									array(
										'id'         => 'list_template',
										'type'       => 'layout_preset',
										'class'      => 'img_custom_width',
										'title'      => esc_html__('Content Position', 'eventful'),
										'subtitle' => esc_html__('Set a position for the event content.', 'eventful'),
										'options'    => array(
											'left_thumb'  => array(
												'image' => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/left.svg',
												'text'  => esc_html__('Left Image', 'eventful'),
												'option_demo_url' => EVENTFUL_DEMO_URL . 'events-minimal-list/#left-image',
											),
											'right_thumb' => array(
												'image' => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/right.svg',
												'text'  => esc_html__('Right Image', 'eventful'),
												'option_demo_url' => EVENTFUL_DEMO_URL . 'events-minimal-list/#right-image',
												'pro_only' => true,
											),
										),
										'default'    => 'left_thumb',
										'dependency' => array(
											array('eventful_layout_preset', 'any', 'list_layout,minimal_list', 'any'),
										)
									),
									array(
										'id'       => 'event_content_sorter',
										'type'     => 'sortable',
										'class'    => 'event_content_sorter',
										'title'    => esc_html__('Sortable Event Elements', 'eventful'),
										'title_help' => '<div class="eventful-info-content">' . __('Drag and drop elements to reorder them, and enable or disable items to control what appears in the event layout.', 'eventful') . '</div><a class="tooltip_btn_primary" target="_blank" href="' . esc_url(EVENTFUL_DEMO_URL . 'docs/display-options/?ref=1#template-styles') . '">' . esc_html__('Open Docs', 'eventful') . '</a><a class="tooltip_btn_secondary" target="_blank" href="' . esc_url(EVENTFUL_DEMO_URL . '/event-content-positions/#content_position') . '">' . esc_html__('Demo', 'eventful') . '</a>',
										'dependency' => array(
											array('template_style', '==', 'custom', 'any'),
										),
										'fields'   => array(
											array(
												'id'         => 'eventful_event_thumb',
												'type'       => 'accordion',
												'accordions' => array(
													array(
														'title'  => esc_html__('Event Thumbnial', 'eventful'),
														'fields' => array(
															array(
																'id'       => 'event_thumb_show',
																'type'     => 'switcher',
																'title'    => esc_html__('Thumbnail', 'eventful'),
																'text_on'  => esc_html__('Show', 'eventful'),
																'text_off' => esc_html__('Hide', 'eventful'),
																'default'  => true,
																'text_width' => 80,
															),
															array(
																'id'      => 'eventful_thumb_sizes',
																'type'    => 'image_sizes',
																'title'   => esc_html__('Size', 'eventful'),
																'default' => 'custom',
																'dependency' => array('event_thumb_show|eventful_layout_preset', '==|not-any', 'true|slider', true),
															),
															array(
																'id'       => 'eventful_image_crop_size',
																'type'     => 'dimensions_advanced',
																'title'    => esc_html__('Custom Size', 'eventful'),
																'desc' => esc_html__('Set custom width and height, choose crop style.', 'eventful'),
																'chosen'   => true,
																'bottom'   => false,
																'left'     => false,
																'color'    => false,
																'top_icon' => '<i class="icofont-long-arrow-left"></i><i class="icofont-long-arrow-right"></i>',
																'right_icon' => '<i class="icofont-long-arrow-up"></i><i class="icofont-long-arrow-down"></i>',
																'top_placeholder' => 'width',
																'right_placeholder' => 'height',
																'styles'   => array(
																	'Soft-crop',
																	'Hard-crop',
																),
																'default'  => array(
																	'top'  => '600',
																	'right' => '400',
																	'style' => esc_html__('Hard-crop', 'eventful'),
																	'unit' => 'px',
																),
																'attributes' => array(
																	'min' => 0,
																),
																'dependency' => array('event_thumb_show|eventful_layout_preset|eventful_thumb_sizes', '==|not-any|==', 'true|slider|custom', true),
															),
															array(
																'id'      => 'eventful_slider_thumb_sizes',
																'type'    => 'image_sizes',
																'title'   => esc_html__('Size', 'eventful'),
																'default' => 'full',
																'dependency' => array('event_thumb_show|eventful_layout_preset', '==|any', 'true|slider', true),
															),
															array(
																'id'       => 'eventful_slider_image_crop_size',
																'type'     => 'dimensions_advanced',
																'title'    => esc_html__('Custom Size', 'eventful'),
																'desc' => esc_html__('Set custom width and height, choose crop style.', 'eventful'),
																'chosen'   => true,
																'bottom'   => false,
																'left'     => false,
																'color'    => false,
																'top_icon' => '<i class="icofont-long-arrow-left"></i><i class="icofont-long-arrow-right"></i>',
																'right_icon' => '<i class="icofont-long-arrow-up"></i><i class="icofont-long-arrow-down"></i>',
																'top_placeholder' => 'width',
																'right_placeholder' => 'height',
																'styles'   => array('Soft-crop', 'Hard-crop'),
																'default'  => array(
																	'top'  => '600',
																	'right' => '400',
																	'style' => esc_html__('Hard-crop', 'eventful'),
																	'unit' => 'px',
																),
																'attributes' => array('min' => 0),
																'dependency' => array('event_thumb_show|eventful_layout_preset|eventful_slider_thumb_sizes', '==|any|==', 'true|slider|custom', true),
															),
															array(
																'id'       => 'load_2x_image',
																'type'     => 'switcher',
																'title'    => esc_html__('Load 2x Resolution Image in Retina Display', 'eventful'),
																'text_on'  => esc_html__('Enabled', 'eventful'),
																'text_off' => esc_html__('Disabled', 'eventful'),
																'text_width' => 94,
																'default'  => false,
																'dependency' => array('event_thumb_show|eventful_thumb_sizes', '==|==', 'true|custom'),
															),
															array(
																'id'      => 'eventful_thumb_src_replace',
																'type'    => 'checkbox',
																'class'   => 'custom_help_text',
																'title'   => esc_html__('Replace With', 'eventful'),
																'desc' => esc_html__('This will replace your default/featured image with the first resource (image/video/audio) from content.', 'eventful'),
																'options' => array(
																	'image'   => esc_html__('Image (Pro)', 'eventful'),
																	'video'   => esc_html__('Video (Pro)', 'eventful'),
																	'audio'   => esc_html__('Audio (Pro)', 'eventful'),
																),
																'dependency' => array('event_thumb_show', '==', 'true'),
															),
															array(
																'id'      => 'post_featured_thumb_found',
																'type'    => 'select',
																'title'   => ' ',
																'options' => array(
																	'no_featured_img_found' => esc_html__('If no featured image found', 'eventful'),
																	'even_featured_img_found' => esc_html__('Even featured image was found', 'eventful'),
																),
																'default' => 'no_featured_img_found',
																'dependency' => array('event_thumb_show|eventful_thumb_src_replace', '==|any', 'true|image,video,audio'),
															),

															array(
																'id'      => 'event_thumb_border',
																'type'    => 'border',
																'title'   => esc_html__('Border', 'eventful'),
																'all'     => true,
																'default' => array(
																	'all' => '0',
																	'style' => 'solid',
																	'color' => '#dddddd',
																),
																'dependency' => array('event_thumb_show', '==', 'true'),
															),
															array(
																'id'       => 'event_thumb_border_radius',
																'type'     => 'spacing',
																'title'    => esc_html__('Border Radius', 'eventful'),
																'desc' => esc_html__('Set border radius for the thumbnail.', 'eventful'),
																'sanitize' => 'eventful_sanitize_number_array_field',
																'default'  => array(
																	'top'    => '0',
																	'right'  => '0',
																	'bottom' => '0',
																	'left'   => '0',
																	'unit'   => 'px',
																),
																'dependency' => array('event_thumb_show', '==', 'true'),
															),

															array(
																'id'      => 'event_thumb_zoom',
																'type'    => 'select',
																'title'   => esc_html__('Zoom Effect', 'eventful'),
																'desc' => esc_html__('Choose a zoom effect for the thumbnail.', 'eventful'),
																'options' => array(
																	'none' => esc_html__('None', 'eventful'),
																	'zoom_in' => esc_html__('Zoom In (Pro)', 'eventful'),
																	'zoom_out' => esc_html__('Zoom Out (Pro)', 'eventful'),
																),
																'default' => 'none',
																'dependency' => array('event_thumb_show', '==', 'true'),
															),
															array(
																'id'      => 'event_thumb_gray_scale',
																'type'    => 'select',
																'title'   => esc_html__('Image Mode', 'eventful'),
																'desc' => esc_html__('Choose grayscale effect for the thumbnail.', 'eventful'),
																'options' => array(
																	'none' => esc_html__('Normal', 'eventful'),
																	'gray_and_normal' => esc_html__('Grayscale and normal on hover (Pro)', 'eventful'),
																	'gray_on_hover' => esc_html__('Grayscale on hover (Pro)', 'eventful'),
																	'always_gray' => esc_html__('Always grayscale (Pro)', 'eventful'),
																),
																'default' => 'none',
																'dependency' => array('event_thumb_show', '==', 'true'),
															),
															array(
																'id'       => 'eventful_img_lazy_load',
																'type'     => 'switcher',
																'class'    => 'switcher_pro_only',
																'title'    => esc_html__('Lazy Load', 'eventful'),
																'desc' => esc_html__('Defer image loading to improve performance.', 'eventful'),
																'text_on'  => esc_html__('Enabled', 'eventful'),
																'text_off' => esc_html__('Disabled', 'eventful'),
																'text_width' => 100,
																'dependency' => array('event_thumb_show|eventful_layout_preset', '==|!=', 'true|carousel_layout', true),
															),
															array(
																'id'       => 'thumbnail_background',
																'type'     => 'color',
																'title'    => esc_html__('Thumbnail Background', 'eventful'),
																'default'  => '#fff',
																'dependency' => array('event_thumb_show', '==', 'true', true),
															),
															array(
																'id'       => 'event_thumb_margin',
																'type'     => 'spacing',
																'title'    => esc_html__('Margin', 'eventful'),
																'desc' => esc_html__('Set margin around the thumbnail.', 'eventful'),
																'sanitize' => 'eventful_sanitize_number_array_field',
																'units'    => array('px'),
																'min'      => -100,
																'default'  => array(
																	'top'  => '0',
																	'right' => '0',
																	'bottom' => '15',
																	'left' => '0',
																),
																'dependency' => array('event_thumb_show', '==', 'true'),
															),
														),
													),
												),
											),
											array(
												'id'         => 'eventful_event_title',
												'type'       => 'accordion',
												'accordions' => array(
													array(
														'title'  => esc_html__('Event Title', 'eventful'),
														'fields' => array(
															array(
																'id'       => 'show_event_title',
																'type'     => 'switcher',
																'title'    => esc_html__('Title', 'eventful'),
																'text_on'  => esc_html__('Show', 'eventful'),
																'text_off' => esc_html__('Hide', 'eventful'),
																'default'  => true,
																'text_width' => 80,
															),
															array(
																'id'      => 'event_title_tag',
																'type'    => 'select',
																'title'   => esc_html__('Title HTML Tag', 'eventful'),
																'desc' => esc_html__('Select the HTML tag for the event title.', 'eventful'),
																'options' => array(
																	'h1'  => esc_html__('h1', 'eventful'),
																	'h2'  => esc_html__('h2', 'eventful'),
																	'h3'  => esc_html__('h3', 'eventful'),
																	'h4'  => esc_html__('h4', 'eventful'),
																	'h5'  => esc_html__('h5', 'eventful'),
																	'h6'  => esc_html__('h6', 'eventful'),
																	'p'   => esc_html__('p', 'eventful'),
																	'div' => esc_html__('div', 'eventful'),
																),
																'default' => 'h2',
																'class'   => 'chosen',
																'dependency' => array('show_event_title', '==', 'true', true),
															),
															array(
																'id'      => 'event_title_limit',
																'type'    => 'checkbox',
																'title'   => esc_html__('Limit Character', 'eventful'),
																'desc' => esc_html__('Enable to limit the number of characters in the title.', 'eventful'),
																'default' => false,
																'dependency' => array('show_event_title', '==', 'true'),
															),
															array(
																'id'              => 'eventful_title_length',
																'type'            => 'spacing',
																'title'           => __('Title Length', 'eventful'),
																'subtitle'        => __('Leave it empty to show full event title.', 'eventful'),
																'all'             => true,
																'all_placeholder' => '',
																'all_icon'        => '',
																'default'         => array(
																	'all'  => '',
																	'unit' => 'words',
																),
																'units'           => array('words', 'characters', 'lines'),
																'attributes'      => array(
																	'min' => 1,
																),
																'dependency' => array('event_title_limit|show_event_title', '==|==', 'true|true'),
															),
															array(
																'id'       => 'event_title_margin',
																'type'     => 'spacing',
																'title'    => esc_html__('Title Margin', 'eventful'),
																'desc' => esc_html__('Set margin around the event title.', 'eventful'),
																'sanitize' => 'eventful_sanitize_number_array_field',
																'min'      => -100,
																'units'    => array('px'),
																'default'  => array(
																	'top'  => '0',
																	'right' => '15',
																	'bottom' => '15',
																	'left' => '15',
																),
																'dependency' => array('show_event_title', '==', 'true'),
															),
														),
													),
												),
											),
											array(
												'id'         => 'eventful_event_meta',
												'type'       => 'accordion',
												'accordions' => array(
													array(
														'title'  => esc_html__('Event Meta Fields', 'eventful'),
														'fields' => array(
															array(
																'id'       => 'show_event_fildes',
																'type'     => 'switcher',
																'title'    => esc_html__('Meta Fields', 'eventful'),
																'desc' => esc_html__('Enable or disable the display of event meta fields.', 'eventful'),
																'text_on'  => esc_html__('Show', 'eventful'),
																'text_off' => esc_html__('Hide', 'eventful'),
																'default'  => true,
																'text_width' => 80,
															),
															array(
																'id'      => 'eventful_event_fildes_group',
																'type'    => 'group',
																'button_title' => esc_html__('Add New Meta', 'eventful'),
																'dependency' => array('show_event_fildes', '==', 'true'),
																'fields'  => array(
																	array(
																		'id'       => 'select_event_fildes',
																		'class'       => 'select_event_fildes',
																		'type'     => 'select',
																		'title'    => esc_html__('Select Meta', 'eventful'),
																		'desc' => esc_html__('Select which meta field to display for this event.', 'eventful'),
																		'placeholder' => esc_html__('Select a meta', 'eventful'),
																		'options'  => array(
																			'venue'     => esc_html__('Venue', 'eventful'),
																			'event_time'     => esc_html__('Event Time', 'eventful'),
																			'price'     => esc_html__('Price', 'eventful'),
																			'organizer'     => esc_html__('Organizer (Pro)', 'eventful'),
																			'taxonomy'     => esc_html__('Taxonomy (Pro)', 'eventful'),
																			'series_archive'     => esc_html__('Series Archive (Pro)', 'eventful'),
																		),
																	),
																	array(
																		'id'       => 'meta_venue_settings',
																		'type'     => 'select',
																		'title'    => esc_html__('Venue Settings', 'eventful'),
																		'desc' => esc_html__('Choose which venue fields to display.', 'eventful'),
																		'placeholder' => esc_html__('Choose an option', 'eventful'),
																		'chosen'   => true,
																		'sortable' => true,
																		'multiple' => true,
																		'options'  => array(
																			'venue_name' => esc_html__('Venue Name', 'eventful'),
																			'address' => esc_html__('Address', 'eventful'),
																			'city' => esc_html__('City', 'eventful'),
																			'country' => esc_html__('Country', 'eventful'),
																			'state' => esc_html__('State', 'eventful'),
																			'postal_code' => esc_html__('Postal Code', 'eventful'),
																			'phone' => esc_html__('Phone', 'eventful'),
																		),
																		'default'     => array('venue_name', 'address'),
																		'dependency' => array('select_event_fildes', '==', 'venue'),
																	),
																	array(
																		'id'      => 'meta_venue_map_link',
																		'type'    => 'switcher',
																		'class'   => 'meta_venue_map_link',
																		'title'   => esc_html__('Show Map Link', 'eventful'),
																		'desc' => esc_html__('Turn on to show a clickable map link for the venue.', 'eventful'),
																		'default' => true,
																		'dependency' => array('select_event_fildes', '==', 'venue'),
																	),
																	array(
																		'id'      => 'select_event_fildes_icon',
																		'class'      => 'eventful-options',
																		'type'    => 'icon',
																		'title'   => esc_html__('Meta Icon', 'eventful'),
																		'desc' => esc_html__('Select an icon to display for this meta field.', 'eventful'),
																		'default' => 'icofont-folder',
																	),
																	array(
																		'id'      => 'event_meta_fildes_date_type',
																		'type'    => 'radio',
																		'title'   => esc_html__('Date Type', 'eventful'),
																		'desc' => esc_html__('Choose how the event date should be displayed.', 'eventful'),
																		'class'   => 'event_meta_fildes_date_type',
																		'options' => array(
																			'start_date' => esc_html__('Start Date and Time', 'eventful'),
																			'end_date' => esc_html__('End Date and Time', 'eventful'),
																			'start_date_time_with_end_date_time' => esc_html__('Start Date Time With End Date Time', 'eventful'),
																		),
																		'default' => 'start_date_time_with_end_date_time',
																		'dependency' => array('select_event_fildes', '==', 'event_time'),
																	),
																	array(
																		'id'    => 'event_meta_fildes_date_format',
																		'type'    => 'select',
																		'title' => ' ',
																		'class' => 'event_meta_fildes_date_format',
																		'options' => array(
																			'j F, Y g:i A' => esc_html__('Default (01 January 2025 12:00 AM)', 'eventful'),
																			'F j, Y g:i A' => esc_html__('(January 01 2025 12:00 AM)', 'eventful'),
																			'F j, g:i A' => esc_html__('(January 01 12:00 AM)', 'eventful'),
																			'j F, g:i A' => esc_html__('( 01 January 12:00 AM)', 'eventful'),
																			'j M, g:i A' => esc_html__('( 01 Jan 12:00 AM)', 'eventful'),
																			'M j, g:i A' => esc_html__('( Jan 01 12:00 AM)', 'eventful'),
																			'j F, Y' => esc_html__('(01 January 2025)', 'eventful'),
																			'F j, Y' => esc_html__('(January 01 2025)', 'eventful'),
																			'M j, Y' => esc_html__('(Jan 01 2025)', 'eventful'),
																			'j M, Y' => esc_html__('(01 Jan 2025)', 'eventful'),
																			'g:i A' => esc_html__('(12:50 AM)', 'eventful'),
																			'G:i' => esc_html__('(23:00)', 'eventful'),
																			'custom' => esc_html__('Custom', 'eventful'),
																		),
																		'default'   => esc_html__('j F, Y g:i A', 'eventful'),
																		'desc' => esc_html__('To define format, check ', 'eventful') . '<a href="https://wordpress.org/support/article/formatting-date-and-time/" target="_blank" rel="noopener noreferrer nofollow"><em>' . esc_html__('this doc', 'eventful') . '</em></a>.',
																		'dependency' => array('select_event_fildes', '==', 'event_time'),
																	),
																	array(
																		'id'    => 'event_meta_fildes_custom_date_format',
																		'type'  => 'text',
																		'title' => ' ',
																		'placeholder' => esc_html__('j F, Y g:i A', 'eventful'),
																		'default'   => esc_html__('j F, Y g:i A', 'eventful'),
																		'desc' => esc_html__('To define format, check', 'eventful') . '<a href="https://wordpress.org/support/article/formatting-date-and-time/" target="_blank" rel="noopener noreferrer nofollow"><em>' . esc_html__('this doc', 'eventful') . '</em></a>.',
																		'dependency' => array('select_event_fildes|event_fildes_date_format', '==|==', 'event_time|custom'),
																	),

																	array(
																		'id'      => 'eventful_meta_select_taxonomy',
																		'type'    => 'select',
																		'title'   => esc_html__('Select Taxonomy', 'eventful'),
																		'desc' => esc_html__('Select which taxonomy to display for the event.', 'eventful'),
																		'options' => array(
																			'tribe_events_cat'	=> esc_html__('Event Categories', 'eventful'),
																			'post_tag'	=> esc_html__('Event Tags', 'eventful'),
																		),
																		'class' => 'eventful_post_taxonomy',
																		'attributes' => array(
																			'style' => 'width: 200px;',
																		),
																		'empty_message' => esc_html__('No taxonomies found.', 'eventful'),
																		'dependency' => array('select_event_fildes', '==', 'taxonomy'),
																	),
																),


																'default' => array(
																	array(
																		'select_event_fildes'    => 'venue',
																		'select_event_fildes_icon'    => 'icofont-google-map',
																		'meta_venue_settings'    => array('venue_name', 'address'),
																	),
																	array(
																		'select_event_fildes'     => 'event_time',
																		'event_meta_fildes_date_type' => 'start_date_time_with_end_date_time',
																		'event_meta_fildes_date_format' => 'j F, Y g:i A',
																		'select_event_fildes_icon'    => 'icofont-clock-time',
																	),
																	array(
																		'select_event_fildes'     => 'price',
																		'select_event_fildes_icon'    => 'icofont-ticket',
																	),
																),
															),
															array(
																'id'      => 'event_meta_separator',
																'type'    => 'radio',
																'title'   => esc_html__('Event Meta Separator', 'eventful'),
																'desc' => esc_html__('Choose the separator between meta fields.', 'eventful'),
																'options' => array(
																	' '  => esc_html__('Normal Space ', 'eventful'),
																	'. ' => esc_html__('Full Stop ( . ) ', 'eventful'),
																	'| ' => esc_html__('Straight Line ( | )', 'eventful'),
																	'/ ' => esc_html__('Slash ( / )', 'eventful'),
																	'\ ' => esc_html__('Back Slash( \\ )', 'eventful'),
																),
																'default' => ' ',
																'dependency' => array('show_event_fildes', '==', 'true'),
															),
															array(
																'id'       => 'event_meta_margin',
																'type'     => 'spacing',
																'title'    => esc_html__('Event Meta Margin', 'eventful'),
																'desc' => esc_html__('Set margin around the event meta container.', 'eventful'),
																'sanitize' => 'eventful_sanitize_number_array_field',
																'units'    => array('px'),
																'min'      => -100,
																'dependency' => array('show_event_fildes', '==', 'true'),
																'default'  => array(
																	'top'  => '0',
																	'right' => '15',
																	'bottom' => '10',
																	'left' => '15',
																),
															),
															array(
																'id'       => 'event_meta_between_margin',
																'type'     => 'spacing',
																'title'    => esc_html__('Margin Between Event Meta', 'eventful'),
																'desc' => esc_html__('Set spacing between individual meta fields.', 'eventful'),
																'sanitize' => 'eventful_sanitize_number_array_field',
																'units'    => array('px'),
																'min'      => -5,
																'dependency' => array('show_event_fildes', '==', 'true'),
																'default'  => array(
																	'top'  => '0',
																	'right' => '5',
																	'bottom' => '5',
																	'left' => '0',
																),
															),
														),
													),
												),
											),
											array(
												'id'         => 'eventful_event_content',
												'type'       => 'accordion',
												'accordions' => array(
													array(
														'title'  => esc_html__('Event Content', 'eventful'),
														'fields' => array(
															array(
																'id'       => 'show_event_content',
																'type'     => 'switcher',
																'title'    => esc_html__('Event Content', 'eventful'),
																'desc' => esc_html__('Enable or disable event content display.', 'eventful'),
																'text_on'  => esc_html__('Show', 'eventful'),
																'text_off' => esc_html__('Hide', 'eventful'),
																'default'  => true,
																'text_width' => 80,
															),
															array(
																'id'      => 'post_content_type',
																'type'    => 'button_set',
																'title'   => esc_html__('Content Display Type', 'eventful'),
																'desc' => esc_html__('Select how the event content should be displayed.', 'eventful'),
																'options' => array(
																	'excerpt'      => esc_html__('Excerpt', 'eventful'),
																	'limit_content' => esc_html__('Content with Limit', 'eventful'),
																	'full_content' => esc_html__('Full Content', 'eventful'),
																),
																'default' => 'limit_content',
																'dependency' => array('show_event_content', '==', 'true'),
															),
															array(
																'id'              => 'eventful_content_length',
																'type'            => 'spacing',
																'title'           => __('Content Length', 'eventful'),
																'subtitle'        => __('Leave it empty to show full event content.', 'eventful'),
																'all'             => true,
																'all_placeholder' => '',
																'all_icon'        => '',
																'default'         => array(
																	'all'  => '20',
																	'unit' => 'words',
																),
																'units'           => array('words', 'characters', 'lines'),
																'attributes'      => array(
																	'min' => 1,
																),
																'dependency' => array('show_event_content|post_content_type', '==|==', 'true|limit_content'),
															),
															array(
																'id'       => 'event_content_margin',
																'type'     => 'spacing',
																'title'    => esc_html__('Event Content Margin', 'eventful'),
																'desc' => esc_html__('Set margin around the event content.', 'eventful'),
																'sanitize' => 'eventful_sanitize_number_array_field',
																'units'    => array('px'),
																'min'      => -100,
																'default'  => array(
																	'top'  => '0',
																	'right' => '15',
																	'bottom' => '15',
																	'left' => '15',
																),
																'dependency' => array('show_event_content', '==', 'true'),
															),
															array(
																'id'      => 'eventful_strip_tags',
																'type'    => 'radio',
																'title'   => esc_html__('HTML Tags', 'eventful'),
																'desc' => esc_html__('Choose whether to allow or strip HTML tags in the content.', 'eventful'),
																'options' => array(
																	'allow_all'  => esc_html__('Allow All', 'eventful'),
																	'strip_all'  => esc_html__('Strip All', 'eventful'),
																	'allow_some' => esc_html__('Allow Some', 'eventful'),
																),
																'default' => 'allow_all',
																'dependency' => array('show_event_content|post_content_type', '==|!=', 'true|excerpt'),
															),
															array(
																'id'    => 'eventful_allow_tag_name',
																'type'  => 'text',
																'title' => esc_html__('Allow HTML Tags Names', 'eventful'),
																'desc' => esc_html__('Separate multiple tags by comma, e.g., h1,h2', 'eventful'),
																'dependency' => array('show_event_content|eventful_strip_tags', '==|==', 'true|allow_some'),
															),
															array(
																'id'      => 'post_content_ellipsis',
																'type'    => 'text',
																'title'   => esc_html__('Ellipsis Points Ending Excerpt', 'eventful'),
																'desc' => esc_html__('Set the ellipsis text at the end of the excerpt.', 'eventful'),
																'default' => '...',
																'dependency' => array('show_event_content|post_content_type', '==|!=', 'true|full_content'),
															),
															array(
																'id'       => 'show_read_more',
																'type'     => 'switcher',
																'title'    => esc_html__('Read More', 'eventful'),
																'desc' => esc_html__('Enable or disable the Read More button/text.', 'eventful'),
																'text_on'  => esc_html__('Show', 'eventful'),
																'text_off' => esc_html__('Hide', 'eventful'),
																'default'  => true,
																'text_width' => 80,
															),
															array(
																'id'      => 'read_more_type',
																'type'    => 'button_set',
																'title'   => esc_html__('Read More Type', 'eventful'),
																'desc' => esc_html__('Choose whether the Read More is displayed as a button or text link.', 'eventful'),
																'options' => array(
																	'button'    => esc_html__('Button', 'eventful'),
																	'text_link' => esc_html__('Text Link', 'eventful'),
																),
																'default' => 'button',
																'dependency' => array('show_read_more', '==', 'true'),
															),
															array(
																'id'      => 'eventful_read_label',
																'type'    => 'text',
																'title'   => esc_html__('Read More Label', 'eventful'),
																'desc' => esc_html__('Set the text label for the Read More button or link.', 'eventful'),
																'default' => 'Read More',
																'dependency' => array('show_read_more', '==', 'true'),
															),
															array(
																'id'      => 'readmore_color_button',
																'type'    => 'color_group',
																'title'   => esc_html__('Read More Color', 'eventful'),
																'desc' => esc_html__('Set the colors for the Read More button.', 'eventful'),
																'options' => array(
																	'text' => esc_html__('Text Color', 'eventful'),
																	'hover_text' => esc_html__('Text Hover Color', 'eventful'),
																	'bg' => esc_html__('Background', 'eventful'),
																	'hover_bg' => esc_html__('Hover Background', 'eventful'),
																),
																'dependency' => array('show_read_more|read_more_type', '==|==', 'true|button'),
															),
															array(
																'id'       => 'read_more_btn_border',
																'type'     => 'border',
																'title'    => esc_html__('Read more Button Border', 'eventful'),
																'desc' => esc_html__('Configure the Read More button border and hover color.', 'eventful'),
																'all'      => true,
																'border_radius' => true,
																'hover_color' => true,
																'show_units'    => true,
																'units'         => 'px',
																'default'       => array(
																	'all'   => '1',
																	'style' => 'solid',
																	'color' => '',
																	'hover_color' => '',
																	'border_radius' => '0',
																	'unit'  => 'px',
																),
																'dependency' => array('show_read_more|read_more_type', '==|==', 'true|button'),
															),
															array(
																'id'       => 'readmore_padding',
																'type'     => 'spacing',
																'title'    => esc_html__('Button Padding', 'eventful'),
																'desc' => esc_html__('Set padding inside the Read More button.', 'eventful'),
																'sanitize' => 'eventful_sanitize_number_array_field',
																'units'    => array('px'),
																'min'      => -100,
																'default'  => array(
																	'top'  => '7',
																	'right' => '15',
																	'bottom' => '7',
																	'left' => '15',
																),
																'dependency' => array('show_read_more|read_more_type', '==|==', 'true|button'),
															),
															array(
																'id'       => 'event_readmore_margin',
																'type'     => 'spacing',
																'title'    => esc_html__('Event Read More Margin', 'eventful'),
																'desc' => esc_html__('Set margin around the Read More button.', 'eventful'),
																'sanitize' => 'eventful_sanitize_number_array_field',
																'units'    => array('px'),
																'min'      => -100,
																'default'  => array(
																	'top'  => '0',
																	'right' => '15',
																	'bottom' => '15',
																	'left' => '15',
																),
																'dependency' => array('show_read_more|read_more_type', '==|==', 'true|button'),
															),
															array(
																'id'      => 'readmore_color_text',
																'type'    => 'color_group',
																'title'   => esc_html__('Read More Color', 'eventful'),
																'desc' => esc_html__('Set the text color for the Read More text link.', 'eventful'),
																'options' => array(
																	'color' => esc_html__('Text Color', 'eventful'),
																	'hover_color' => esc_html__('Text Hover Color', 'eventful'),
																),
																'dependency' => array('show_read_more|read_more_type', '==|==', 'true|text_link'),
															),
														),
													),
												),
											),

											array(
												'id'         => 'eventful_event_social_share',
												'type'       => 'accordion',
												'accordions' => array(
													array(
														'title'  => esc_html__('Event Social Share', 'eventful'),
														'fields' => array(
															array(
																'id'       => 'show_social_media',
																'type'     => 'switcher',
																'title'    => esc_html__('Sharing Media', 'eventful'),
																'desc' => esc_html__('Enable or disable social sharing icons.', 'eventful'),
																'text_on'  => esc_html__('Show', 'eventful'),
																'text_off' => esc_html__('Hide', 'eventful'),
																'default'  => true,
																'text_width' => 80,
															),
															array(
																'id'       => 'social_sharing_media',
																'type'     => 'select',
																'title'    => esc_html__('Select Sharing Media', 'eventful'),
																'desc' => esc_html__('Select which social media icons to display.', 'eventful'),
																'chosen'   => true,
																'sortable' => true,
																'multiple' => true,
																'placeholder' => esc_html__('Choose an option', 'eventful'),
																'options'  => array(
																	'facebook' => esc_html__('Facebook', 'eventful'),
																	'twitter' => esc_html__('Twitter', 'eventful'),
																	'linkedIn' => esc_html__('LinkedIn', 'eventful'),
																	'email' => esc_html__('Email', 'eventful'),
																	'whatsapp' => esc_html__('WhatsApp', 'eventful'),
																	'pinterest' => esc_html__('Pinterest (Pro)', 'eventful'),
																	'instagram' => esc_html__('Instagram (Pro)', 'eventful'),
																	'vk'   => esc_html__('VK (Pro)', 'eventful'),
																	'digg' => esc_html__('digg (Pro)', 'eventful'),
																	'tumblr' => esc_html__('Tumblr (Pro)', 'eventful'),
																	'reddit' => esc_html__('Reddit (Pro)', 'eventful'),
																	'pocket' => esc_html__('Pocket (Pro)', 'eventful'),
																	'xing' => esc_html__('Xing (Pro)', 'eventful'),
																),
																'dependency' => array('show_social_media', '==', 'true'),
															),
															array(
																'id'      => 'social_icon_shape',
																'class'   => 'social_icon_shape',
																'type'    => 'layout_preset',
																'type'    => 'layout_preset',
																'title'   => esc_html__('Icon Shape', 'eventful'),
																'desc' => esc_html__('Choose the shape of social media icons.', 'eventful'),
																'options' => array(
																	'efp_circle'    => array(
																		'image'       => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/circle-icon.png',
																		'text' => esc_html__('Circle', 'eventful'),
																		'option_demo_url' => '',
																	),
																	'efp_rounded'   => array(
																		'image'       => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/round-icon.png',
																		'text' => esc_html__('Rounded', 'eventful'),
																		'option_demo_url' => '',
																	),
																	'efp_square'    => array(
																		'image'       => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/square-icon.png',
																		'text' => esc_html__('Square', 'eventful'),
																		'option_demo_url' => '',
																	),
																	'icon_only' => array(
																		'image'       => EVENTFUL_DIR_URL . 'src/Admin/Framework/assets/img/only-icon.png',
																		'text' => esc_html__('Icon only', 'eventful'),
																		'option_demo_url' => '',
																	),
																),
																'default' => 'efp_circle',
																'dependency' => array('show_social_media|social_sharing_media', '==|!=', 'true|'),
															),
															array(
																'id'      => 'social_icon_custom_color',
																'type'    => 'button_set',
																'title'   => esc_html__('Custom Color', 'eventful'),
																'desc' => esc_html__('Choose between original icon colors or custom colors.', 'eventful'),
																'options'	=> array(
																	'original' => array(
																		'text' => esc_html__('Original', 'eventful'),
																	),
																	'custom'   => array(
																		'text' => esc_html__('Custom', 'eventful'),
																		'pro_only' => true,
																	),
																),
																'default' => 'original',
																'dependency' => array('show_social_media|social_sharing_media', '==|!=', 'true|'),
															),
															array(
																'id'      => 'social_position',
																'type'    => 'button_set',
																'title'   => esc_html__('Alignment', 'eventful'),
																'desc' => esc_html__('Set the alignment for social media icons.', 'eventful'),
																'options'    => array(
																	'inherit'   => '<i class="icofont-refresh" title="Left"></i>',
																	'left'   => '<i class="icofont-align-left" title="Left"></i>',
																	'center' => '<i class="icofont-align-center" title="Center"></i>',
																	'right'  => '<i class="icofont-align-right" title="Right"></i>',
																),
																'default' => 'inherit',
																'dependency' => array('show_social_media|social_sharing_media', '==|!=', 'true|'),
															),
															array(
																'id'       => 'social_margin',
																'type'     => 'spacing',
																'title'    => esc_html__('Margin', 'eventful'),
																'desc' => esc_html__('Set margin around the social media icons.', 'eventful'),
																'sanitize' => 'eventful_sanitize_number_array_field',
																'min'      => -100,
																'units'    => array('px'),
																'default'  => array(
																	'top'  => '0',
																	'right' => '15',
																	'bottom' => '15',
																	'left' => '15',
																),
																'dependency' => array('show_social_media|social_sharing_media', '==|!=', 'true|'),
															),
														),
													),
												),
											),
											array(
												'id'         => 'eventful_custom_fields',
												'type'       => 'accordion',
												'class'       => 'pro_only',
												'accordions' => array(
													array(
														'title'  => esc_html__('Custom Fields (Pro)', 'eventful'),
														'fields' => array(), // End Fields array.
													),
												), // Accordion.
											), // Custom fields end.
										),
									),

									array(
										'id'       => 'eventful_background_overlay',
										'type'     => 'color',
										'title'    => esc_html__('Overlay Background', 'eventful'),
										'subtitle' => esc_html__('Set background color for the item.', 'eventful'),
										'default'  => 'rgba(20,20,31,0.5)',
										'dependency' => array('eventful_layout_preset|content_template_style|template_style', 'any|==|==', 'carousel_layout,grid_layout,ticker,center,multi-rows|overlay|custom', true),
									),

									array(
										'id'         => 'theme_style',
										'class'      => 'theme_style_grid',
										'preview'    => true,
										'type'       => 'select',
										'title'      => esc_html__('Template Style ', 'eventful'),
										'title_help' => '<div class="eventful-info-label">' . esc_html__('Choose from available ready-made templates to control how events are displayed.', 'eventful') . '</div><a class="tooltip_btn_primary" target="_blank" href="' . esc_url(EVENTFUL_DEMO_URL . 'docs/display-options/?ref=1#template-styles') . '">' . esc_html__('Open Docs', 'eventful') . '</a> <a class="tooltip_btn_secondary" target="_blank" href="' . esc_url(EVENTFUL_DEMO_URL . 'pre-made-event-templates/') . '">' . esc_html__('Demo', 'eventful') . '</a>',
										'options'    => array(
											'theme-one'   => esc_html__('Template One', 'eventful'),
											'theme-two'   => esc_html__('Template Two', 'eventful'),
											'theme-three' => esc_html__('Template Three', 'eventful'),
										),
										'default'    => 'theme-one',
										'dependency' => array('eventful_layout_preset|template_style', 'not-any|==', 'list_layout,minimal_list|pre-made', 'any'),
									),

									// Meta Background & Text Color
									array(
										'id'       => 'event_thumb_meta_color',
										'type'     => 'color_group',
										'title'    => esc_html__('Theme Color Shims', 'eventful'),
										'subtitle' => esc_html__('Set theme color shims.', 'eventful'),
										'options'  => array(
											'featured' => esc_html__('Featured', 'eventful'),
											'non_featured'    => esc_html__('Non Featured', 'eventful'),
										),
										'dependency' => array('template_style', 'any|!=|==', 'pre-made'),
									),

									array(
										'id'      => 'thumbnail_size',
										'type'    => 'image_sizes',
										'title'   => esc_html__('Thumbnail Size', 'eventful'),
										'default' => 'custom',
										'dependency' => array('eventful_layout_preset|template_style', 'not-any|==', 'slider|pre-made', true)
									),
									array(
										'id'       => 'thumbnail_custom_size',
										'type'     => 'dimensions_advanced',
										'title'    => esc_html__('Custom Size', 'eventful'),
										'desc' => esc_html__('Set custom width and height, choose crop style.', 'eventful'),
										'chosen'   => true,
										'bottom'   => false,
										'left'     => false,
										'color'    => false,
										'top_icon' => '<i class="icofont-long-arrow-left"></i><i class="icofont-long-arrow-right"></i>',
										'right_icon' => '<i class="icofont-long-arrow-up"></i><i class="icofont-long-arrow-down"></i>',
										'top_placeholder' => 'width',
										'right_placeholder' => 'height',
										'styles'   => array(
											'Soft-crop',
											'Hard-crop',
										),
										'default'  => array(
											'top'  => '600',
											'right' => '400',
											'style' => esc_html__('Hard-crop', 'eventful'),
											'unit' => 'px',
										),
										'attributes' => array(
											'min' => 0,
										),
										'dependency' => array('eventful_layout_preset|template_style|thumbnail_size', 'not-any|==|==', 'slider|pre-made|custom', true),
									),
									array(
										'id'      => 'slider_thumbnail_size',
										'type'    => 'image_sizes',
										'title'   => esc_html__('Slider Thumbnail Size', 'eventful'),
										'default' => 'full',
										'dependency' => array('eventful_layout_preset|template_style', 'any|==', 'slider|pre-made', true),
									),
									array(
										'id'       => 'slider_thumbnail_custom_size',
										'type'     => 'dimensions_advanced',
										'title'    => esc_html__('Custom Size', 'eventful'),
										'desc' => esc_html__('Set custom width and height, choose crop style.', 'eventful'),
										'chosen'   => true,
										'bottom'   => false,
										'left'     => false,
										'color'    => false,
										'top_icon' => '<i class="icofont-long-arrow-left"></i><i class="icofont-long-arrow-right"></i>',
										'right_icon' => '<i class="icofont-long-arrow-up"></i><i class="icofont-long-arrow-down"></i>',
										'top_placeholder' => 'width',
										'right_placeholder' => 'height',
										'styles'   => array(
											'Soft-crop',
											'Hard-crop',
										),
										'default'  => array(
											'top'  => '600',
											'right' => '400',
											'style' => esc_html__('Hard-crop', 'eventful'),
											'unit' => 'px',
										),
										'attributes' => array(
											'min' => 0,
										),
										'dependency' => array('eventful_layout_preset|template_style|slider_thumbnail_size', 'any|==|==', 'slider|pre-made|custom', true),
									),
									array(
										'id'       => 'thumbnail_load_2x',
										'type'     => 'switcher',
										'title'    => esc_html__('Load 2x Resolution Image in Retina Display', 'eventful'),
										'text_on'  => esc_html__('Enabled', 'eventful'),
										'text_off' => esc_html__('Disabled', 'eventful'),
										'text_width' => 94,
										'default'  => false,
										'dependency' => array('template_style|thumbnail_size', '==|==', 'pre-made|custom'),
									),
									array(
										'id'       => 'thumb_border',
										'type'     => 'border',
										'title'    => esc_html__('Thumbnail Border', 'eventful'),
										'title_help' => esc_html__('Configure the thumbnail border.', 'eventful'),
										'all'      => true,
										'border_radius' => true,
										'show_units'    => true,
										'units'         => 'px',
										'default'       => array(
											'all'   => '2',
											'style' => 'solid',
											'color' => 'gray',
											'border_radius' => '5',
											'unit'  => 'px',
										),
										'dependency' => array(
											array('eventful_layout_preset', '==', 'minimal_list', 'any'),
											array('template_style', '==', 'pre-made'),
											array('theme_style_minimal_list', '==', 'theme-two'),
										)
									),

									array(
										'id'       => 'content_alignment',
										'type'     => 'button_set',
										'title'    => esc_html__('Alignment', 'eventful'),
										'subtitle' => esc_html__('Set alignment for the meta content.', 'eventful'),
										'options'  => array(
											'left'   => '<i class="icofont-align-left" title="Left"></i>',
											'center' => '<i class="icofont-align-center" title="Center"></i>',
											'right'  => '<i class="icofont-align-right" title="Right"></i>',
										),
										'dependency' => array(
											array('theme_style', 'any', 'theme-two,theme-one,theme-three'),
											array('template_style', 'any|!=|==', 'pre-made'),
										),
									),

									// Meta Options
									// array(
									// 	'id'       => 'event_thumb_left_meta',
									// 	'type'     => 'select',
									// 	'title'    => esc_html__('Meta For Left Side', 'eventful'),
									// 	'subtitle' => esc_html__('Choose which meta you want to display on the event thumbnail.', 'eventful'),
									// 	'placeholder' => esc_html__('Template Specefic', 'eventful'),
									// 	'options'  => array(
									// 		'none' 			=> esc_html__('Hide', 'eventful'),
									// 		'taxonomy' 		=> esc_html__('Taxonomy', 'eventful'),
									// 		'date'     		=> esc_html__('Date', 'eventful'),
									// 		'venue'     	=> esc_html__('Venue', 'eventful'),
									// 		'organizer'     => esc_html__('Organizer', 'eventful'),
									// 		'social_media'  => esc_html__('Social Media', 'eventful'),
									// 	),
									// 	'dependency' => array('theme_style|template_style', 'any|==', 'theme-one|pre-made'),
									// ),
									// array(
									// 	'id'       => 'event_thumb_meta_taxonomy_left',
									// 	'type'     => 'button_set',
									// 	'title'    => esc_html__('Choose Taxonomy', 'eventful'),
									// 	'subtitle' => esc_html__('Choose which taxonomy to display for the event.', 'eventful'),
									// 	'options'  => array(
									// 		'tribe_events_cat' => esc_html__('Event Categories', 'eventful'),
									// 		'post_tag'         => esc_html__('Event Tags', 'eventful'),
									// 	),
									// 	'default'  => 'tribe_events_cat',
									// 	'dependency' => array('theme_style|event_thumb_left_meta|template_style', 'any|==|==', 'theme-one,theme-two|taxonomy|pre-made'),
									// ),
									// Meta Position
									// array(
									// 	'id'       => 'event_thumb_left_meta_position',
									// 	'type'     => 'button_set',
									// 	'title'    => esc_html__('Left Meta Position', 'eventful'),
									// 	'subtitle' => esc_html__('Select a position for the meta.', 'eventful'),
									// 	'options'  => array(
									// 		''     => esc_html__('Defult', 'eventful'),
									// 		'top_left'     => esc_html__('Top Left', 'eventful'),
									// 		'bottom_left'  => esc_html__('Bottom Left', 'eventful'),
									// 	),
									// 	'default'  => '',
									// 	'dependency' => array('theme_style|event_thumb_left_meta|template_style', 'any|!=|==', 'theme-one|none|pre-made'),
									// ),
									// Meta Options
									// array(
									// 	'id'       => 'event_thumb_right_meta',
									// 	'type'     => 'select',
									// 	'title'    => esc_html__('Meta For Right Side', 'eventful'),
									// 	'subtitle' => esc_html__('Choose which meta you want to display on the event thumbnail.', 'eventful'),
									// 	'placeholder' => esc_html__('Template Specefic', 'eventful'),
									// 	'options'  => array(
									// 		'none' 			=> esc_html__('None', 'eventful'),
									// 		'taxonomy' 		=> esc_html__('Taxonomy', 'eventful'),
									// 		'date'     		=> esc_html__('Date', 'eventful'),
									// 		'venue'     	=> esc_html__('Venue', 'eventful'),
									// 		'organizer'     => esc_html__('Organizer', 'eventful'),
									// 		'social_media'  => esc_html__('Social Media', 'eventful'),
									// 	),
									// 	'dependency' => array('theme_style|template_style', 'any|==', 'theme-one|pre-made'),
									// ),

									// array(
									// 	'id'       => 'event_thumb_meta_taxonomy_right',
									// 	'type'     => 'button_set',
									// 	'title'    => esc_html__('Choose Taxonomy Right', 'eventful'),
									// 	'subtitle' => esc_html__('Choose which taxonomy to display for the event.', 'eventful'),
									// 	'options'  => array(
									// 		'tribe_events_cat' => esc_html__('Event Categories', 'eventful'),
									// 		'post_tag'         => esc_html__('Event Tags', 'eventful'),
									// 	),
									// 	'default'  => 'tribe_events_cat',
									// 	'dependency' => array('theme_style|event_thumb_right_meta|template_style', 'any|==|==', 'theme-one,theme-two|taxonomy|pre-made'),
									// ),

									// Meta Position
									// array(
									// 	'id'       => 'event_thumb_right_meta_position',
									// 	'type'     => 'button_set',
									// 	'title'    => esc_html__('Meta Position Right', 'eventful'),
									// 	'subtitle' => esc_html__('Select a position for the meta.', 'eventful'),
									// 	'options'  => array(
									// 		''    => esc_html__('Default', 'eventful'),
									// 		'top_right'    => esc_html__('Top right', 'eventful'),
									// 		'bottom_right' => esc_html__('Bottom right', 'eventful'),
									// 	),
									// 	'default'  => '',
									// 	'dependency' => array('theme_style|event_thumb_right_meta|template_style', 'any|!=|==', 'theme-one|none|pre-made'),
									// ),

									// array(
									// 	'id'       => 'event_thumb_meta_date_type',
									// 	'type'     => 'radio',
									// 	'title'    => esc_html__('Date Type', 'eventful'),
									// 	'subtitle' => esc_html__('Select which date type to display for the event.', 'eventful'),
									// 	'class'    => 'event_thumb_meta_date_type',
									// 	'options'  => array(
									// 		'start_date' => esc_html__('Start Date and Time', 'eventful'),
									// 		'end_date'   => esc_html__('End Date and Time', 'eventful'),
									// 		'start_date_time_with_end_date_time' => esc_html__('Start Date Time With End Date Time', 'eventful'),
									// 	),
									// 	'default' => 'start_date_time_with_end_date_time',
									// 	'dependency' => array('theme_style|template_style', 'any|==', 'theme-two|pre-made'),
									// ),
									// array(
									// 	'id'       => 'event_thumb_meta_date_format',
									// 	'type'     => 'select',
									// 	'class'    => 'event_thumb_meta_date_format',
									// 	'title'    => esc_html__('Date Format', 'eventful'),
									// 	'desc' => esc_html__('To define format, check ', 'eventful') . '<a href="https://wordpress.org/support/article/formatting-date-and-time/" target="_blank" rel="noopener noreferrer nofollow"><em>' . esc_html__('this doc', 'eventful') . '</em></a>.',
									// 	'options'  => array(
									// 		'j F, Y g:i A' => esc_html__('(01 January 2025 12:00 AM)', 'eventful'),
									// 		'F j, Y g:i A' => esc_html__('(January 01 2025 12:00 AM)', 'eventful'),
									// 		'F j, g:i A' => esc_html__('(January 01 12:00 AM)', 'eventful'),
									// 		'j F, g:i A' => esc_html__('(01 January 12:00 AM)', 'eventful'),
									// 		'j M, g:i A' => esc_html__('(01 Jan 12:00 AM)', 'eventful'),
									// 		'M j, g:i A' => esc_html__('(Jan 01 12:00 AM)', 'eventful'),
									// 		'j F, Y' => esc_html__('(01 January 2025)', 'eventful'),
									// 		'F j, Y' => esc_html__('(January 01 2025)', 'eventful'),
									// 		'M j, Y' => esc_html__('(Jan 01 2025)', 'eventful'),
									// 		'j M, Y' => esc_html__('(01 Jan 2025)', 'eventful'),
									// 		'g:i A' => esc_html__('(12:50 AM)', 'eventful'),
									// 		'G:i' => esc_html__('(23:00)', 'eventful'),
									// 		'custom' => esc_html__('Custom', 'eventful'),
									// 	),
									// 	'default'   => esc_html__('j F, Y', 'eventful'),
									// 	'dependency' => array('theme_style|template_style', 'any|==', 'theme-two|pre-made'),
									// ),
									// array(
									// 	'id'       => 'event_thumb_meta_custom_date_format',
									// 	'type'     => 'text',
									// 	'title'    => esc_html__('Date Format', 'eventful'),
									// 	'subtitle' => '' . esc_html__('To define format, check ', 'eventful') . '<a href="https://wordpress.org/support/article/formatting-date-and-time/" target="_blank" rel="noopener noreferrer nofollow"><em>' . esc_html__('this doc', 'eventful') . '</em></a>.',
									// 	'placeholder' => esc_html__('j F, Y g:i A', 'eventful'),
									// 	'default'  => esc_html__('j F, Y g:i A', 'eventful'),
									// 	'dependency' => array('theme_style|template_style|event_thumb_meta_date_format', 'any|==|==', 'theme-two|pre-made|custom'),
									// ),

									// array(
									// 	'id'       => 'content_element',
									// 	'type'     => 'select',
									// 	'title'    => esc_html__('Content Element(s)', 'eventful'),
									// 	'subtitle' => esc_html__('Choose which content elements to display in the event layout.', 'eventful'),
									// 	'placeholder' => esc_html__('Excerpt & Venue', 'eventful'),
									// 	'options'    => array(
									// 		'only_excerpt' => esc_html__('Excerpt', 'eventful'),
									// 		'only_venue' => esc_html__('Venue', 'eventful'),
									// 		'no_element' => esc_html__('No Element', 'eventful'),
									// 	),
									// 	'dependency' => array(
									// 		array('template_style', 'any|!=|==', 'pre-made'),
									// 	),
									// ),

									// array(
									// 	'id'       => 'event_price_position',
									// 	'type'     => 'select',
									// 	'title'    => esc_html__('Event Price Postion', 'eventful'),
									// 	'subtitle'  => esc_html__('Choose where the event price should be displayed with in readmore button.', 'eventful'),
									// 	'placeholder' => esc_html__('Select Postion', 'eventful'),
									// 	'options'     => array(
									// 		'none' => esc_html__('None', 'eventful'),
									// 		'before_read_more' => esc_html__('Top', 'eventful'),
									// 		'after_read_more'  => esc_html__('Bottom', 'eventful'),
									// 		'left_side'        => esc_html__('Left', 'eventful'),
									// 		'right_side'       => esc_html__('Right', 'eventful'),
									// 	),
									// 	'dependency' => array(
									// 		array('template_style', 'any|!=|==', 'pre-made'),
									// 	),
									// ),

									// array(
									// 	'id'       => 'event_thumb_meta_background',
									// 	'type'     => 'background',
									// 	'title'    => esc_html__('Date Background', 'eventful'),
									// 	'subtitle' => esc_html__('Set the background gradient for the meta area.', 'eventful'),
									// 	'background_gradient' => true,
									// 	'background_origin'   => false,
									// 	'background_clip'     => false,
									// 	'background_blend_mode' => false,
									// 	'background_image'    => false,
									// 	'background_position' => false,
									// 	'background_repeat'   => false,
									// 	'background_attachment' => false,
									// 	'background_size'     => false,
									// 	'background_image_preview' => false,
									// 	'default' => array(
									// 		'background-color'              => 'rgba(0,0,0,.75)',
									// 		'background-gradient-color'     => 'rgba(0,0,0,.75)',
									// 		'background-gradient-direction' => 'to right',
									// 	),
									// 	'dependency' => array(
									// 		array('theme_style', 'any', 'theme-two'),
									// 		array('template_style', 'any|!=|==', 'pre-made'),
									// 	),
									// ),

									array(
										'id'       => 'event_category_display',
										'type'     => 'switcher',
										'title'    => esc_html__('Event Category', 'eventful'),
										'title_help' => esc_html__('Show/Hide event category.', 'eventful'),
										'text_on'  => esc_html__('Show', 'eventful'),
										'text_off' => esc_html__('Hide', 'eventful'),
										'text_width' => 80,
										'default'  => true,
										'class'    => 'switcher_pro_only',
										'dependency' => array(
											array('template_style', 'any', 'pre-made'),
										),
									),
									array(
										'id'       => 'event_title_display',
										'type'     => 'switcher',
										'title'    => esc_html__('Event Title', 'eventful'),
										'title_help' => esc_html__('Show/Hide event title.', 'eventful'),
										'text_on'  => esc_html__('Show', 'eventful'),
										'text_off' => esc_html__('Hide', 'eventful'),
										'text_width' => 80,
										'default'  => true,
										'class'    => 'switcher_pro_only',
										'dependency' => array(
											array('template_style', 'any', 'pre-made'),
										),
									),
									array(
										'id'              => 'template_title_limit',
										'type'            => 'spacing',
										'class'           => 'eventful_title_limit',
										'title'           => __('Title Length', 'eventful'),
										'subtitle'        => __('Leave it empty to show full event title.', 'eventful'),
										'all'             => true,
										'all_placeholder' => '',
										'all_icon'        => '',
										'only_pro'        => true,
										'default'         => array(
											'all'  => '',
											'unit' => 'Words (Pro)',
										),
										'units'           => array('Words (Pro)', 'Characters (Pro)', 'Lines (Pro)'),
										'attributes'      => array(
											'min' => 1,
										),
										'dependency' => array(
											array('template_style', 'any', 'pre-made'),
											array('event_title_display', '==', 'true'),
										),
									),
									array(
										'id'       => 'event_content_display',
										'type'     => 'switcher',
										'title'    => esc_html__('Event Content', 'eventful'),
										'title_help' => esc_html__('Show/Hide event content.', 'eventful'),
										'text_on'  => esc_html__('Show', 'eventful'),
										'text_off' => esc_html__('Hide', 'eventful'),
										'text_width' => 80,
										'default'  => true,
										'class'    => 'switcher_pro_only',
										'dependency' => array(
											array('eventful_layout_preset', '!=', 'minimal_list', true),
											array('template_style', 'any', 'pre-made'),
										),
									),
									array(
										'id'      => 'template_content_type',
										'type'    => 'button_set',
										'title'   => esc_html__('Content Display Type', 'eventful'),
										'desc' => esc_html__('Select how the event content should be displayed.', 'eventful'),
										'options' => array(
											'excerpt'      => esc_html__('Excerpt', 'eventful'),
											'limit_content' => esc_html__('Content with Limit', 'eventful'),
											'full_content' => esc_html__('Full Content', 'eventful'),
										),
										'default' => 'limit_content',
										'dependency' => array(
											array('eventful_layout_preset', '!=', 'minimal_list', true),
											array('template_style', 'any', 'pre-made'),
											array('event_content_display', '==', 'true'),
										),
									),
									array(
										'id'              => 'template_content_length_type',
										'type'            => 'spacing',
										'class'           => 'eventful_title_limit',
										'title'           => __('Content Length', 'eventful'),
										'subtitle'        => __('Leave it empty to show full event content.', 'eventful'),
										'all'             => true,
										'all_placeholder' => '',
										'all_icon'        => '',
										'default'         => array(
											'all'  => '30',
											'unit' => 'Words (Pro)',
										),
										'units'           => array('Words (Pro)', 'Characters (Pro)', 'Lines (Pro)'),
										'attributes'      => array(
											'min' => 1,
										),
										'dependency' => array(
											array('eventful_layout_preset', '!=', 'minimal_list', true),
											array('template_style', 'any', 'pre-made'),
											array('event_content_display', '==', 'true'),
											array('template_content_type', '==', 'limit_content'),
										),
									),
									array(
										'id'       => 'event_venue_display',
										'type'     => 'switcher',
										'title'    => esc_html__('Event Venue', 'eventful'),
										'title_help' => esc_html__('Show/Hide event venue.', 'eventful'),
										'text_on'  => esc_html__('Show', 'eventful'),
										'text_off' => esc_html__('Hide', 'eventful'),
										'text_width' => 80,
										'default'  => true,
										'class'    => 'switcher_pro_only',
										'dependency' => array(
											array('eventful_layout_preset', '!=', 'minimal_list', true),
											array('template_style', 'any', 'pre-made'),
										),
									),
									array(
										'id'       => 'event_read_more_button_display',
										'type'     => 'switcher',
										'title'    => esc_html__('Event Read More Button', 'eventful'),
										'title_help' => esc_html__('Show/Hide event read more button.', 'eventful'),
										'text_on'  => esc_html__('Show', 'eventful'),
										'text_off' => esc_html__('Hide', 'eventful'),
										'text_width' => 80,
										'default'  => true,
										'class'    => 'switcher_pro_only',
										'dependency' => array(
											array('eventful_layout_preset', '!=', 'minimal_list', true),
											array('template_style', 'any', 'pre-made'),
										),
									),
									array(
										'id'       => 'event_read_more_button_label',
										'type'     => 'text',
										'title'    => esc_html__('Event Read More Button Label', 'eventful'),
										'title_help' => esc_html__('Set the label for the event read more button.', 'eventful'),
										'default'  => esc_html__('Read More', 'eventful'),
										'dependency' => array(
											array('eventful_layout_preset', '!=', 'minimal_list', true),
											array('template_style', 'any', 'pre-made'),
											array('event_read_more_button_display', '==', 'true'),
										),
									),
									array(
										'id'       => 'event_price_display',
										'type'     => 'switcher',
										'title'    => esc_html__('Event Price', 'eventful'),
										'title_help' => esc_html__('Show/Hide event price.', 'eventful'),
										'text_on'  => esc_html__('Show', 'eventful'),
										'text_off' => esc_html__('Hide', 'eventful'),
										'text_width' => 80,
										'default'  => true,
										'dependency' => array(
											array('eventful_layout_preset', '!=', 'minimal_list', true),
											array('template_style', 'any', 'pre-made'),
										),
									),
								),
							),
							array(
								'title' => esc_html__('Pagination', 'eventful'),
								'icon'  => 'icofont-spinner-alt-5',
								'dependency' => array('eventful_layout_preset', 'not-any', 'carousel_layout,slider', true),
								'fields' => array(
									array(
										'id'         => 'show_post_pagination',
										'type'       => 'switcher',
										'title'      => esc_html__('Pagination', 'eventful'),
										'subtitle' => esc_html__('Enable or disable item pagination.', 'eventful'),
										'text_on'    => esc_html__('Enabled', 'eventful'),
										'text_off'   => esc_html__('Disabled', 'eventful'),
										'text_width' => 100,
										'default'    => true,
										'dependency' => array('eventful_layout_preset', 'not-any', 'carousel_layout,slider', true),
									),

									array(
										'id'         => 'event_pagination_type',
										'type'       => 'radio',
										'title'      => esc_html__('Pagination Type', 'eventful'),
										'subtitle' => esc_html__('Select how pagination should behave on desktop view.', 'eventful'),
										'desc'   => esc_html__('More amazing Ajax Pagination Settings are available in ', 'eventful') .
											'<a href="https://wpeventful.com/pricing/" target="_blank"><strong>' . esc_html__('Pro', 'eventful') . '</strong></a>!',
										'options'    => array(
											'ajax_load_more'  => esc_html__('Load More Button (Ajax)', 'eventful'),
											'ajax_pagination' => esc_html__('Ajax Number Pagination (Pro)', 'eventful'),
											'infinite_scroll' => esc_html__('Infinite Scroll (Ajax) (Pro)', 'eventful'),
											'no_ajax'         => esc_html__('No Ajax (Normal Pagination) (Pro)', 'eventful'),
										),
										'default'    => 'ajax_load_more',
										'dependency' => array('eventful_layout_preset|show_post_pagination', 'not-any|==', 'carousel_layout,filter_layout|true', true),
									),
									array(
										'id'         => 'filter_pagination_type',
										'type'       => 'radio',
										'title'      => esc_html__('Filter Pagination Type', 'eventful'),
										'subtitle' => esc_html__('Select the pagination type for filtered results.', 'eventful'),
										'options'    => array(
											'ajax_load_more'  => esc_html__('Load More Button (Ajax)', 'eventful'),
											'infinite_scroll' => esc_html__('Infinite Scroll (Ajax)', 'eventful'),
										),
										'default'    => 'ajax_load_more',
										'dependency' => array('eventful_layout_preset|show_post_pagination', '==|==', 'filter_layout|true', true),
									),
									array(
										'id'         => 'event_pagination_type_mobile',
										'type'       => 'select',
										'title'      => esc_html__('Pagination Type for Mobile', 'eventful'),
										'subtitle' => esc_html__('Choose pagination behavior for mobile devices.', 'eventful'),
										'options'    => array(
											'ajax_load_more'  => esc_html__('Load More Button (Ajax)', 'eventful'),
											'ajax_pagination' => esc_html__('Ajax Pagination (Pro)', 'eventful'),
											'infinite_scroll' => esc_html__('Infinite Scroll (Ajax) (Pro)', 'eventful'),
											'no_ajax'         => esc_html__('No Ajax (Normal Pagination) (Pro)', 'eventful'),
										),
										'default'    => 'ajax_load_more',
										'dependency' => array('eventful_layout_preset|show_post_pagination', 'not-any|==', 'carousel_layout,filter_layout|true', true),
									),
									array(
										'id'         => 'load_more_button_text',
										'type'       => 'text',
										'title'      => esc_html__('Load More Button Label', 'eventful'),
										'subtitle' => esc_html__('Set the label for the Load More button.', 'eventful'),
										'default'    => esc_html__('Load More', 'eventful'),
										'dependency' => array('eventful_layout_preset|show_post_pagination', '!=|==', 'carousel_layout|true', true),
									),
									array(
										'id'         => 'load_more_ending_message',
										'type'       => 'text',
										'title'      => esc_html__('Ending Message', 'eventful'),
										'subtitle' => esc_html__('Message shown when there are no more events to load.', 'eventful'),
										'default'    => esc_html__('No more events available', 'eventful'),
										'dependency' => array('eventful_layout_preset|show_post_pagination', '!=|==', 'carousel_layout|true', true),
									),

									array(
										'id'         => 'eventful_loadmore_btn_color',
										'type'       => 'color_group',
										'title'      => esc_html__('Load More Button Color', 'eventful'),
										'subtitle' => esc_html__('Customize text, hover text, border, and background colors for the Load More button.', 'eventful'),
										'options'    => array(
											'text_color'        => esc_html__('Text Color', 'eventful'),
											'text_hcolor'       => esc_html__('Text hover Color', 'eventful'),
											'border_color'      => esc_html__('Border Color', 'eventful'),
											'border_hcolor'     => esc_html__('Border Hover Color', 'eventful'),
											'background'        => esc_html__('Background', 'eventful'),
											'active_background' => esc_html__('Hover Background', 'eventful'),
										),
										'dependency' => array('eventful_layout_preset|show_post_pagination|event_pagination_type', '!=|==|==', 'carousel_layout|true|ajax_load_more', true),
									),
									array(
										'id'         => 'pagination_alignment',
										'type'       => 'button_set',
										'title'      => esc_html__('Alignment', 'eventful'),
										'subtitle' => esc_html__('Align pagination to left, center, or right.', 'eventful'),
										'options'    => array(
											'left'   => wp_kses(__('<i class="icofont-align-left" title="Left"></i>', 'eventful'), array('i' => array('class' => array()))),
											'center' => wp_kses(__('<i class="icofont-align-center" title="Center"></i>', 'eventful'), array('i' => array('class' => array()))),
											'right'  => wp_kses(__('<i class="icofont-align-right" title="Right"></i>', 'eventful'), array('i' => array('class' => array()))),
										),
										'default'    => 'left',
										'dependency' => array('eventful_layout_preset|show_post_pagination', '!=|==', 'carousel_layout|true', true),
									),
									array(
										'id'         => 'post_per_page',
										'type'       => 'spinner',
										'title'      => esc_html__('Items Per Page', 'eventful'),
										'subtitle' => esc_html__('This value should be lesser than the Limit set in the Filter Events tab.', 'eventful'),
										'sanitize'   => 'eventful_sanitize_number_field',
										'default'    => 12,
										'dependency' => array('eventful_layout_preset|show_post_pagination', '!=|==', 'carousel_layout|true', true),
									),
								)
							),
						)
					),
				), // End of fields array.
			)
		); // Display settings section end.
	}
}
