<?php if ( !count( (array) $post->choices ) ): ?>
  No choices found.
<?php else: ?>
  <table class="wp-list-table widefat fixed striped posts">
    <thead>
      <tr>
        <td width="1%">&nbsp;</td>
        <td width="4%">ID</td>
        <td width="10%">Date</td>
        <td width="10%">User</td>
        <td width="14%">Label</td>
        <td width="29%">Description</td>
        <td width="5%">URL</td>
        <td width="5%">Image</td>
        <td width="11%">&nbsp;</td>
        <td width="11%">&nbsp;</td>
      </tr>
    </thead>
    <tbody>
      <?php foreach ( $post->choices as $post ): ?>
        <tr data-post-id="<?php echo $post->ID ?>" id="<?php echo $post->ID ?>">
          <td class="drag-icon">-<br>-<br>-</td>
          <td><?php echo $post->ID ?></td>
          <td><?php echo $post->post_date ?></td>
          <td><?php if ( $post->user_id ) echo get_the_author_meta( 'display_name', $post->user_id ) ?></td>
          <td><?php echo $post->choice_label ?></td>
          <td><?php echo apply_filters( 'the_content', $post->post_content ) ?></td>
          <td><?php echo ( $post->choice_url ) ? '<a href="'. $post->choice_url .'" target="_blank">URL</a>' : '&nbsp;' ?></td>
          <td><?php echo ( $post->choice_image ) ? '<a href="'. $post->choice_image .'" target="_blank">Image</a>' : '&nbsp;' ?></td>
          <td style="text-align: center;"><a href="#" class="open-poll-choice-modal" data-choice-id="<?php echo $post->ID ?>" data-entry-id="<?php echo $post->post_parent ?>">edit</a></td>
          <td style="text-align: center;"><a href="#" class="poll-choice-delete" data-choice-id="<?php echo $post->ID ?>">delete</a></td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
<?php endif; ?>